config/routes.rb
Rails.application.routes.draw do
  root 'friends#index'
  get 'pages/show'
  resources :friends
  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user, optional: true
  has_many :item_values, dependent: :destroy
  has_many :item_basics, dependent: :destroy
  validates :user_id, presence: true
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :sign_in_required, only: [:new,:edit,:index,:show]
  before_action :friend
  def index
  end

  def new
    @Friend = Friend.new
    @ItemBasics = ItemBasic.new
  end

  def create
    @Friend = current_user.friends.build
    @ItemBasics = @Friend.item_basics.build(user_params)
    if @Friend.save && @ItemBasics.save
      redirect_to friends_path
    else
      render 'new'
    end
  end

  def edit
    @ItemBasics = ItemBasic.find(params[:id])
  end

  def show
    @ItemBasics = ItemBasic.find(params[:id])
  end

  def update
    @ItemBasics = ItemBasic.find(params[:id])
    if @ItemBasics.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to friend_path
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:item_basic).permit(:name,:sex,:birthday,:meet,:tel,:url,:company,:address,
                                     :birthplace,:twitter,:facebook,:instagram,:line,:linkedin)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/edit.html.erb
<h1>編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 form-horizontal">
    <%= form_for(@ItemBasics,url: friend_path) do |f| %>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "名前" %>
        </label>
        <div class="col-sm-7 ">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "性別" %>
        </label>
        <div class="col-sm-7">
          <%= f.radio_button :sex, 1 %>男 <%= f.radio_button :sex, 2 %>女
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "誕生日" %>
        </label>
        <div class="col-sm-7">
          <%= f.date_field :birthday %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "出会った場所" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :meet %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "電話番号" %>
        </label>
        <div class="col-sm-7">
          <%= f.telephone_field :tel %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "URL" %>
        </label>
        <div class="col-sm-7">
          <%= f.url_field :url %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "会社" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :company %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "住所" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :address %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "出身" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :birthplace %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "Twitter" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :twitter %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "Facebook" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :facebook %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "Instagram" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :instagram %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "LINE" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :line %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "LinkedIn" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :linkedin %>
        </div>
      </div>
      <div class="col-sm-offset-4 col-sm-8">
        <%= f.submit "完了", class: "btn btn-warning col-sm-7 btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <div class="center jumbotron">
  <h2>こんにちは、<%= current_user.username %>さん</h2>
  <p>Chiki!は知己になった友達・仲間を記録していくアプリケーションです</p>
    <%= link_to "新規作成", new_friend_path , class: "btn btn-lg btn-warning"%>
 </div>
<% else %>
<div class="center jumbotron">
  <h1>Chiki!へようこそ！</h1>
  <p>Chiki!は出会った友達・仲間を記録していくアプリケーションです</p>
  <p><%= Settings.sample[:sample]%></p>

  <%= link_to "アカウント作成", new_user_registration_path, class: "btn btn-lg btn-warning" %>
  <%= link_to "ログイン", new_user_session_path, class: "btn btn-lg btn-outline-warning" %>
</div>

<% end %>

app/views/friends/new.html.erb
<h1>新規作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 form-horizontal">
    <%= form_for(@ItemBasics,url: friends_path) do |f| %>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "名前" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "性別" %>
        </label>
        <div class="col-sm-7">
          <%= f.radio_button :sex, 1 %>男 <%= f.radio_button :sex, 2 %>女
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "誕生日" %>
        </label>
        <div class="col-sm-7">
          <%= f.date_field :birthday %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "出会った場所" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :meet %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "電話番号" %>
        </label>
        <div class="col-sm-7">
          <%= f.telephone_field :tel %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "URL" %>
        </label>
        <div class="col-sm-7">
          <%= f.url_field :url %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "会社" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :company %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "住所" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :address %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "出身" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :birthplace %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "Twitter" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :twitter %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "Facebook" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :facebook %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "Instagram" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :instagram %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "LINE" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :line %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-5 control-label">
          <%= f.label "LinkedIn" %>
        </label>
        <div class="col-sm-7">
          <%= f.text_field :linkedin %>
        </div>
      </div>
      <div class="col-sm-offset-4 col-sm-8">
        <%= f.submit "作成", class: "btn btn-warning col-sm-7 btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/friends/show.html.erb
<p>名前： <%= @ItemBasics.name %></p>
<% if @ItemBasics.sex == 1 %>
  <p>性別： 男</p>
<% elsif @ItemBasics.sex == 2 %>
  <p>性別： 女</p>
<% end %>
<p>誕生日： <%= @ItemBasics.birthday %></p>
<p>出会った場所： <%= @ItemBasics.meet %></p>
<p>電話番号： <%= @ItemBasics.tel %></p>
<p>URL： <%= @ItemBasics.url %></p>
<p>会社： <%= @ItemBasics.company %></p>
<p>現住所： <%= @ItemBasics.address %></p>
<p>出身： <%= @ItemBasics.birthplace %></p>
<p>Twitter： <%= @ItemBasics.twitter %></p>
<p>Facebook： <%= @ItemBasics.facebook %></p>
<p>Instagram： <%= @ItemBasics.instagram %></p>
<p>LINE： <%= @ItemBasics.line %></p>
<p>LinkedIn： <%= @ItemBasics.linkedin %></p>

<%= link_to "編集", edit_friend_path %>