config/routes.rb
Rails.application.routes.draw do
  root 'friends#index'
  get 'pages/show'
  resources :friends
  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default drawer-navbar" role="banner">
  <div class="container">

    <% if false %>
      <div id="header">
        <div class="nav-left">
            <div id="head-logo">
                <%= link_to image_tag('coollogo_com-7026956.png'), friends_path %>
            </div>
        </div>
      </div>
    <% end %>

    <nav>
      <% if user_signed_in? %>
      <%# ドロワーメニュー %>
       <ul class="nav navbar-nav navbar-left">
        <div id="nav-drawer">
            <input id="nav-input" type="checkbox" class="nav-unshown">
            <label id="nav-open" for="nav-input"><span></span></label>
            <label class="nav-unshown" id="nav-close" for="nav-input"></label>
            <div id="nav-content">
              <div class="drawer-menu">
                <div class="drawer-name">
                  <%= link_to "新規作成", new_friend_path %>
                </div>
                <% @friends.each do |friend| %>
                  <div class="drawer-name">
                    <%= link_to friend.name, friend_path(friend) %>
                  </div>
                <% end %>
              </div>
            </div>
        </div>
      </ul>

      <%# タイトルロゴ %>
      <%= link_to "Chiki!", friends_path, id: "logo" %>

      <%# <ul class="nav navbar-nav navbar-right "> %>
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-home" aria-hidden="true"></span> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu left">
              <li><%= link_to 'ホーム', friends_path %></li>
              <li><%= link_to current_user.username, pages_show_path %></li>
              <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
      <%# </ul> %>
    <% else %>
    <%= link_to "Chiki!", friends_path, id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'アカウント作成', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
      </ul>
      <% end %>
    </nav>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
   　　<%= render 'layouts/flash' %>

      <%= yield %>
    </div>
  </body>
</html>